# 📊 Prometheus Configuration for Production Monitoring
# Comprehensive metrics collection for Kickstarter Investment Tracker

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend API metrics
  - job_name: 'kickstarter-backend'
    static_configs:
      - targets: ['backend:8001']
    metrics_path: '/api/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # System metrics (node exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # MongoDB metrics (if using local instance)
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'

  # Custom application metrics
  - job_name: 'kickstarter-custom-metrics'
    static_configs:
      - targets: ['backend:8001']
    metrics_path: '/api/admin/metrics'
    scrape_interval: 30s
